#ifndef LSYSTEM
#define LSYSTEM

#include "Turtle.h"
#include "CompiledProduction.h"
#include "FlatModule.h"
#include <string>
#include <vector>
#include <stack>
#include <list>
#include <map>
#include <utility>
#include <algorithm>

using namespace std;

enum NodeType { isLeaf, isBranch, noModules };

class Texture
{
public:
    string name;
    vector<pair<string, float> > parameters;
};

// Defines a node in the L-System derivation tree representing a plant module
class Node
{
public:
    // State
    bool alive;
    bool newBorn;
    NodeType nodeType;

    // Time
    float currentAge;
    float initialAge;
    float terminalAge;
    float moduleLifeSpan;

    // Grammar
    list<Node* > children;
    map<string, string>::value_type* production;
    list<pair<char, Turtle> > turtleCache;

    // Geometry
    Turtle tortoise; // turtle state after this production

    vector<vector<float> > branchSegment;
    // branchSegment[0] = start position (x,y,z)
    // branchSegment[1] = end position (x,y,z)
    // branchSegment[2][0] = colorIndex
    // branchSegment[3][0] = diameter

    vector<vector<float> > leaf;
    // leaf[0][0] = number of vertices _n_ in polygon
    // leaf[1] = end position (x,y,z) of first vertex
    // . . .
    // leaf[n] = end position (x,y,z) of last vertex
    // leaf[n+1][0] = colorIndex

    Node() { nodeType = noModules; newBorn = true; 	alive = true; currentAge = 0.0f; }
};

class LSystem
{
    // Geometry
    Turtle* tortoise;
    vector<vector<float> > currentPolygon;
    float fDistance;	// current distance to move turtle forward with 'f' or 'F'
    float deltaAngle;	// angle by which to change turtle heading
    float diameter;	// current branch segment diameter
    float deltaDiameter; // amount by which to branch diameter

    // Grammar
    string axiom;	// start variable or axiom for L-System
    string word;	// current sting or word generated by L-System
    map<string, string> productions;
    map<char, string> successorTable;	// look up table mapping the single letter
    // in a timed word successor to the full
    // string for that successor e.g. "I" -> "(I,1)"

    // Pre-compiled command arrays for each production
    map<string, CompiledProduction> compiledProductions;
    void compileAllProductions();

    // Derivation
    class Node* root = nullptr;	// root of the derivation tree
    void traverseDTree(Node* aNode);
    Node* createModule(map<string, string>::value_type* production, float initialAge, Turtle& parentTurtle);
    void subdivideModule(Node* aNode);
    void interpretProduction(Node* aNode);
    void interpretProductionCompiled(Node* aNode);
    void createRootModule();
    void flattenTree(Node* aNode);

    // State
    bool readingPolygon;
    stack<Turtle> turtleStack;

    // Time
    float deltaTime;
    float startTime;	// specified in global time
    float plantLifeSpan;

    // Colors
    int numColors;

    // Debugging
    bool display;

public:
    // Time
    float age;

    // Geometry data
    float xPos;
    float zPos;
    vector<FlatModule> flatModules;
    uint32_t nextNodeIndex;

    // Textures
    vector<Texture*> textures;

    LSystem(float xPos, float zPos, float fDistance, float deltaAngle, float diameter, float deltaDiameter,
            string axiom, map<string, string> productions, float startTime, float deltaTime, float plantLifeSpan,
            int numColors, vector<Texture*> textures, bool debug);
    ~LSystem();
    void step(float currentGlobalTime);
};

#endif // !LSYSTEM
